### ISSUE TITLE
Decide for experiment tracking packages

### ISSUE THREAD

**Issue by ravivanpong** [ravivanpong/CausalBench#2]
Desirable features

- Can be used with Python and R
- Open source
- Save data, hyperparameters, parameters for synthetic data simulation, metrics
- Dash board
- Export as .csv for analysis

Candidates

- [ ]  [sacred ](https://github.com/IDSIA/sacred)
- [ ]  [MLflow](https://mlflow.org/)
- [ ]  [Guild](https://guild.ai/)
- [ ]  [ClearML](https://github.com/allegroai/clearml)

Please explain why and why not we should use the package.

**Comment by ravivanpong** [comment]
For simplicity, just output everything into csv for later analysis.
